export const siteConfig = {
  name: "Rijschool Ren\u00e9 van der Vegt",
  shortName: "Ren\u00e9 van der Vegt",
  location: "Apeldoorn",
  regionDescription: "Apeldoorn en omgeving",
  city: "Apeldoorn",
  address: "Musketiersveld 23",
  postalCode: "7327 GV",
  phone: "0630133335",
  phoneDisplay: "06 301 333 35",
  phoneHref: "tel:+31630133335",
  whatsappHref: "https://wa.me/31630133335",
  email: "info@rvandervegt.nl",
  emailHref: "mailto:info@rvandervegt.nl",
  url: "https://rvandervegt.nl",
  contactUrl: "https://rvandervegt.nl",
  signupUrl: "https://rvandervegt.nl",
  privacyUrl: "https://rvandervegt.nl",
  googleReviewsUrl: "https://www.google.com/maps/search/?api=1&query=Rijschool+Ren\u00e9+van+der+Vegt+Apeldoorn",
  slogan: "RIS \u2014 rijopleiding in stappen",
  rating: "4,9",
  reviewCount: 35,
} as const;
